#!/bin/bash

#add 
#post-up /etc/failover/vm_subnet_change
# to /etc/network/interfaces

vm_id=103

subnets="2a01:4f8:13b:1a9e:: 2a01:4f8:13b:1a9f:: 2a01:4f8:13b:1aa0::"
gateway_postfix=2
nic=ens18

current_gateway=$(ip -6 route | grep default | awk '{ print $3 }')

if ! ping -c3 $current_gateway > /dev/null 2>&1
then
	echo fail
	for subnet in $subnets
	do
		current_ip=$(ip addr show $nic | grep inet6 | awk '{print $2}' | head -n 1)
		ip addr delete $current_ip dev $nic
		ip addr add $subnet$vm_id/64 dev $nic
		ip route change default via $subnet$gateway_postfix
		if ping -c3 $subnet$gateway_postfix > /dev/null 2>&1
		then
			break
		fi
	done
fi

